// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLibrary.Models;

namespace MyLibrary.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyLibrary.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BookAuthor1")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BookAuthor2")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BookCategory")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BookEdition")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BookISBN")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BookPublisher")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("BookPurchasePrice")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("BookStatus")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BookStorage_Code")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BookStorage_Type")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
